import assert from 'node:assert/strict';
import { openLightbox, initLightbox } from '../site/assets/lightbox.js';
import { setItems, setFiltered } from '../site/assets/state.js';
const node = () => ({ hidden:false, dataset:{}, value:'', options:[], textContent:'', classList:{ add(){},remove(){} },
 addEventListener(){},setAttribute(){},removeAttribute(name){delete this[name];},
 replaceChildren(){this.options=[];},append(option){this.options.push(option);},
 focus(){document.activeElement=this;},querySelectorAll(){return [];} });
const els = Object.fromEntries(['lightbox','lbClose','lbImg','lbTitle','lbCopyright','lbNote','lbRes','lbLink','lbDownload','lbCopy','lbCopyMd','lbPrev','lbNext','lbStatus','lbRetry'].map(key=>[key,node()]));
els.lightbox.hidden = true;
globalThis.document = {documentElement:{lang:'zh-CN',dataset:{}},body:{style:{}},activeElement:node(),addEventListener(){},createElement:node};
globalThis.window = {addEventListener(){}};
globalThis.location = {search:'',pathname:'/'};
let pushes=0;
globalThis.history = {state:null,pushState(state,title,url){pushes++;location.search=url;},replaceState(state,title,url){location.search=url.startsWith('?')?url:'';}};
initLightbox(els);
const item={date:'20200101',title:'测试图片',thumbnail:'./thumb.webp'};
setItems([item]);setFiltered([item]);
let fail;
globalThis.fetch=()=>new Promise((resolve,reject)=>{fail=reject;});
const opening=openLightbox(item,els);
assert.equal(els.lightbox.hidden,false);
assert.equal(els.lightbox.dataset.loadState,'loading');
assert.equal(document.body.style.overflow,'hidden');
assert.equal(document.activeElement,els.lbClose);
fail(new Error('HTTP 503'));await opening;
assert.equal(els.lightbox.dataset.loadState,'error');
assert.equal(els.lbRetry.hidden,false);
assert.match(els.lbStatus.textContent,/加载失败/);
assert.equal(pushes,1);
console.log('✓ 首次加载失败时显示灯箱与重试入口');
globalThis.fetch=async()=>({ok:true,json:async()=>[{...item,url:'https://example.test/image_1920x1080.jpg',uhd:false}]});
await els.lbRetry.onclick();
assert.equal(els.lightbox.dataset.loadState,'ready');assert.equal(els.lbRetry.hidden,true);
assert.equal(els.lbStatus.textContent,'');assert.equal(pushes,1);
assert.match(els.lbImg.src,/image_1920x1080/);
console.log('✓ 重试恢复图片且不会重复推入浏览历史');
els.lbClose.onclick();await Promise.resolve();
assert.equal(els.lightbox.hidden,true);assert.equal(document.body.style.overflow,'');
let lateFail;
globalThis.fetch=()=>new Promise((resolve,reject)=>{lateFail=reject;});
const old=openLightbox({date:'20190101',title:'旧请求'},els);
els.lbClose.onclick();await Promise.resolve();
await openLightbox({...item,url:'https://example.test/new.jpg'},els);
lateFail(new Error('HTTP 503'));await old;
assert.equal(els.lightbox.dataset.loadState,'ready');assert.equal(els.lbStatus.textContent,'');
assert.equal(els.lbRetry.hidden,true);
console.log('✓ 关闭后的旧请求失败不会覆盖新图片');
els.lbClose.onclick();await Promise.resolve();
let lateSuccess;
globalThis.fetch=()=>new Promise(resolve=>{lateSuccess=resolve;});
const pending=openLightbox({date:'20180101',title:'关闭前加载'},els);
els.lbClose.onclick();await Promise.resolve();
lateSuccess({ok:true,json:async()=>[]});await pending;
assert.equal(els.lightbox.hidden,true);assert.equal(document.body.style.overflow,'');
console.log('✓ 关闭后完成的请求不会重新打开灯箱');
